// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 7ca3799b8b5f1acde1dd7a8dfb7ae849d3dfb4cd

package data

var LanguagesGroup = map[string]string{}
