// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 7ca3799b8b5f1acde1dd7a8dfb7ae849d3dfb4cd

package data

var LanguagesMime = map[string]string{
	"C#":           "text/x-csharp",
	"C++":          "text/x-c++src",
	"CSS":          "text/css",
	"Clojure":      "text/x-clojure",
	"CoffeeScript": "text/x-coffeescript",
	"Dockerfile":   "text/x-dockerfile",
	"F#":           "text/x-fsharp",
	"Go":           "text/x-go",
	"HTML":         "text/html",
	"INI":          "text/x-properties",
	"Java":         "text/x-java",
	"JavaScript":   "text/javascript",
	"Less":         "text/css",
	"Lua":          "text/x-lua",
	"Markdown":     "text/x-gfm",
	"Objective-C":  "text/x-objectivec",
	"PHP":          "application/x-httpd-php",
	"Perl":         "text/x-perl",
	"PowerShell":   "application/x-powershell",
	"Pug":          "text/x-pug",
	"Python":       "text/x-python",
	"R":            "text/x-rsrc",
	"Ruby":         "text/x-ruby",
	"Rust":         "text/x-rustsrc",
	"SCSS":         "text/x-scss",
	"SQL":          "text/x-sql",
	"Scheme":       "text/x-scheme",
	"Shell":        "text/x-sh",
	"Swift":        "text/x-swift",
	"TypeScript":   "application/typescript",
	"XML":          "text/xml",
	"YAML":         "text/x-yaml",
}
